CREATE DATABASE IF NOT EXISTS we_mp_rss CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'rss_user'@'%' IDENTIFIED BY 'pass123456';
GRANT ALL PRIVILEGES ON we_mp_rss.* TO 'rss_user'@'%';
FLUSH PRIVILEGES;
